### ISSUE TITLE
UI - "Shambhala" text cut off during start-up of App

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#9] opened 2017-04-01 20:44 UTC
Display of the text "Shambhala" is cut off on the right (middle of the letter "L" & on) when showing on the splash start-up screen.  (using an iPad to test the app)

Maybe, the text & logo is too big for that screen, before the main page is shown.

**Comment by gshotwell** [comment] 2017-04-03 11:41
Duplicate of #20

**Closed as completed by gshotwell** 2017-04-03 11:41 UTC
